server:
  port: 8080
spring:
  application:
    name: chinsmall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: test_gateway
          uri: https://www.baidu.com
          predicates:
#            如果包含url参数，且参数值是百度，则匹配
            - Query=url, baidu



